name: Dev Env - Build Skunk

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@dev
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 8
        java-package: jdk
        architecture: x64
    
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo This is the developement environment
        echo Building Skunk app after every change in dev process.

    - name: Set Permissions on scripts.
      run: chmod u+x *.sh
    # Runs a single command using the runners shell
    - name: Build Source Classes
      run: ./build.sh
